nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  dfinity:
    npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@dfinity/ledger-icp@*":
    dependencies:
      "@dfinity/agent": "^0.20.2"
      "@dfinity/principal": "^0.20.2"
      "@dfinity/candid": "^0.20.2"
  "util@*":
    peerDependencies:
      "process": "*"
  "process@*":
    peerDependencies:
      "util": "*"