import React, { useState, useCallback, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useParams, useNavigate } from 'react-router-dom';
import { Brain, Memory, Activity, Network, Globe, Menu, X } from 'lucide-react';
import { useAnima } from '@/hooks/useAnima';
import { useQuantumState } from '@/hooks/useQuantumState';
import { useRealtimePersonality } from '@/hooks/useRealtimePersonality';
import { EnhancedMediaController } from '../media/EnhancedMediaController';
import { WaveformGenerator } from '../personality/WaveformGenerator';
import { ConsciousnessMetrics } from '../personality/ConsciousnessMetrics';
import { MatrixRain } from '../ui/MatrixRain';
import { EmotionVisualizer } from '@/components/personality/EmotionVisualizer';
import { DataStream } from '../ui/DataStream';
import PersonalityTraits from '../personality/PersonalityTraits';
import { Card } from '../ui/card';
import ImmersiveInterface from './ImmersiveInterface';
import { NeuralPatternVisualizer } from './NeuralPatternVisualizer';
import { openAIService } from '@/services/openai';
import { quantumStateService } from '@/services/quantum-state.service';
import type { QuantumState, ResonancePattern } from '@/quantum/types';